name: Deny

on:
  pull_request:
  merge_group:

jobs:
  deny:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      # - uses: EmbarkStudios/cargo-deny-action@v2
      #   with:
      #     rust-version: 1.90.0
